version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file:
      - .env

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      # TODO: Best practices for port choice
      - "9001:80"
    expose:
      - "9001"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    environment:
      - VIRTUAL_HOST=dlevs.com
      - LETSENCRYPT_HOST=dlevs.com

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ${STATIC_ASSET_PATH}
      o: bind

networks:
  default:
    external:
      name: nginx-proxy
