version: '3.7'

# TODO: Document usage of docker in README
services:
  nodejs:
    build:
      context: .
      # TODO: Eventually change this:
      target: dev-app
    restart: unless-stopped
    env_file:
      - .env
  webserver:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      # TODO: Best practices for port choice
      - "9001:80"
    expose:
      - "9001"
    volumes:
      - ./public:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    environment:
      - VIRTUAL_HOST=dlevs.com
      - LETSENCRYPT_HOST=dlevs.com

networks:
  default:
    external:
      name: nginx-proxy
